language: python
python:
  - "3.11"
dist: focal
services:
  - docker
install: skip
before_script:
  - env > ./postgres/.env
  - env > ./backend/.env
  - env > ./frontend/.env
  - docker-compose -f docker-compose.test.yml up -d --build
script:
  - docker exec backend pytest
  - docker-compose run --rm --no-deps frontend npm test --watchAll=false
  - docker exec nginx nginx -t
after_script:
  - docker-compose down
