language: python
python:
  - "3.12"
dist: focal
services:
  - docker
install: skip
before_script:
  - env > ./backend/.env
  - env > ./frontend/.env
  - docker-compose -f docker-compose.test.yml up -d --build
script:
  - docker exec backend pytest
  - docker exec frontend npm test
  - docker exec nginx nginx -t
after_script:
  - docker-compose down
