language: python
python:
  - "3.9"
dist: focal
services:
  - docker
before_script:
  - env > ./backend/.env
  - env > ./frontend/.env
  - docker-compose up -d --build
script:
  - docker exec backend python manage.py test
  - docker exec frontend npm test --watchAll=false
after_script:
  - docker-compose down
