version: "3.2"
services:
  redis:
    container_name: redis
    image: redis:7
    restart: always
    volumes:
      - redis_data:/data/:rw
    networks:
      - private
  backend:
    container_name: backend
    image: backend
    build:
      context: backend
      dockerfile: test.Dockerfile
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - backend_static:/opt/app/static/:rw
    networks:
      - public
      - private
    depends_on:
      - redis
  frontend:
    container_name: frontend
    image: frontend
    build: frontend
    stdin_open: true
    env_file:
      - ./frontend/.env
    volumes:
      - frontend_static:/opt/app/dist/:rw
    networks:
      - public
    depends_on:
      - backend
  nginx:
    container_name: nginx
    image: nginx:1.23-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - backend_static:/opt/backend/static/:ro
      - frontend_static:/opt/frontend/static/:ro
    networks:
      - public
    depends_on:
      - frontend
volumes:
  redis_data:
  backend_static:
  frontend_static:
networks:
  public:
  private:
