version: "3.2"
services:
  postgres:
    container_name: postgres
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: primality_tester
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data/:rw
  redis:
    container_name: redis
    image: redis:7
    restart: always
    volumes:
      - redis_data:/data/:rw
  backend:
    container_name: backend
    image: backend
    build:
      context: backend
      dockerfile: test.Dockerfile
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - backend_static:/opt/app/static/:rw
    depends_on:
      - postgres
      - redis
  frontend:
    container_name: frontend
    image: frontend
    build: frontend
    env_file:
      - ./frontend/.env
    volumes:
      - frontend_static:/opt/app/build/:rw
    depends_on:
      - backend
  nginx:
    container_name: nginx
    image: nginx:1.23-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - backend_static:/opt/backend/static/:ro
      - frontend_static:/opt/frontend/static/:ro
    depends_on:
      - frontend
volumes:
  postgres_data:
  redis_data:
  backend_static:
  frontend_static:
