name: Docker Build and Push
on:
  push:
    branches:
      - master
jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - context: backend
            tags: ${{ vars.REGISTRY_URL }}/primality_tester_backend
          - context: frontend
            tags: ${{ vars.REGISTRY_URL }}/primality_tester_frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Create frontend environment file
        run: echo "${{ secrets.FRONTEND_ENV_FILE }}" > frontend/.env
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          push: true
          tags: ${{ matrix.tags }}
